"""Legacy CLI parity tests against the STELLOPT ``xneo`` executable."""

from __future__ import annotations

import os
from pathlib import Path
import re
import shutil
import subprocess

import numpy as np
import pytest


REPO = Path(__file__).resolve().parents[2]
REFERENCE_BIN = Path(os.environ.get("NEO_REFERENCE_BIN", str(Path.home() / "bin" / "xneo")))
RUN_SLOW = bool(os.environ.get("NEO_JAX_RUN_SLOW"))


def _format_control_scalar(value: float | int | str) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, int):
        return str(value)
    return format(float(value), ".15g")


def _make_control(
    *,
    out_file: str,
    surfaces: list[int],
    theta_n: int = 8,
    phi_n: int = 8,
    max_m_mode: int = 0,
    max_n_mode: int = 0,
    npart: int = 10,
    multra: int = 1,
    acc_req: float = 0.05,
    no_bins: int = 10,
    nstep_per: int = 5,
    nstep_min: int = 10,
    nstep_max: int = 20,
    calc_nstep_max: int = 0,
    eout_swi: int = 1,
    lab_swi: int = 0,
    inp_swi: int = 0,
    ref_swi: int = 2,
    write_progress: int = 0,
    write_output_files: int = 0,
    spline_test: int = 0,
    write_integrate: int = 0,
    write_diagnostic: int = 0,
    calc_cur: int = 0,
    cur_file: str = "neo_cur",
    npart_cur: int = 200,
    alpha_cur: float = 2.0,
    write_cur_inte: int = 0,
) -> str:
    flux_line = " ".join(str(v) for v in surfaces)
    no_fluxs = len(surfaces)
    return "\n".join(
        [
            "! autogenerated legacy parity case",
            "! line2",
            "! line3",
            "boozmn",
            out_file,
            str(no_fluxs),
            flux_line,
            str(theta_n),
            str(phi_n),
            str(max_m_mode),
            str(max_n_mode),
            str(npart),
            str(multra),
            _format_control_scalar(acc_req),
            str(no_bins),
            str(nstep_per),
            str(nstep_min),
            str(nstep_max),
            str(calc_nstep_max),
            str(eout_swi),
            str(lab_swi),
            str(inp_swi),
            str(ref_swi),
            str(write_progress),
            str(write_output_files),
            str(spline_test),
            str(write_integrate),
            str(write_diagnostic),
            "0",
            "0",
            "0",
            str(calc_cur),
            cur_file,
            str(npart_cur),
            _format_control_scalar(alpha_cur),
            str(write_cur_inte),
            "",
        ]
    )


def _run_neo_pair(tmp_path: Path, *, extension: str) -> tuple[Path, Path]:
    ref_dir = tmp_path / "ref"
    jax_dir = tmp_path / "jax"
    ref_dir.mkdir(exist_ok=True)
    jax_dir.mkdir(exist_ok=True)

    subprocess.run(
        [str(REFERENCE_BIN), extension],
        cwd=ref_dir,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )
    env = os.environ.copy()
    env["PYTHONPATH"] = str(REPO)
    subprocess.run(
        ["python", "-m", "neo_jax", extension],
        cwd=jax_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )
    return ref_dir, jax_dir


def _copy_case(
    tmp_path: Path,
    *,
    extension: str,
    booz_src: Path,
    control_text: str,
    control_filename: str | None = None,
    extra_controls: dict[str, str] | None = None,
) -> None:
    control_filename = control_filename or f"neo_in.{extension}"
    for td in (tmp_path / "ref", tmp_path / "jax"):
        td.mkdir(exist_ok=True)
        (td / control_filename).write_text(control_text, encoding="utf-8")
        shutil.copy2(booz_src, td / f"boozmn_{extension}.nc")
        if extra_controls:
            for name, text in extra_controls.items():
                (td / name).write_text(text, encoding="utf-8")


def _copy_fixture_case(
    tmp_path: Path,
    *,
    fixture_dir: Path,
    extension: str,
    control_name: str,
    booz_name: str | None = None,
) -> None:
    for td in (tmp_path / "ref", tmp_path / "jax"):
        td.mkdir(exist_ok=True)
        shutil.copy2(fixture_dir / control_name, td / control_name)
        source_name = booz_name or f"boozmn_{extension}.nc"
        shutil.copy2(fixture_dir / source_name, td / f"boozmn_{extension}.nc")


def _copy_single_cli_case(tmp_path: Path, *, extension: str, booz_src: Path, control_text: str) -> Path:
    case_dir = tmp_path / "case"
    case_dir.mkdir(exist_ok=True)
    (case_dir / f"neo_in.{extension}").write_text(control_text, encoding="utf-8")
    shutil.copy2(booz_src, case_dir / f"boozmn_{extension}.nc")
    return case_dir


def _load_numeric_file(path: Path) -> np.ndarray:
    return np.fromstring(path.read_text().replace("D", "E"), sep=" ")


def _parse_legacy_float_token(token: str) -> float:
    if token == "NaN":
        return float("nan")
    if token in {"Infinity", "+Infinity"}:
        return float("inf")
    if token == "-Infinity":
        return float("-inf")
    if "E" not in token and "D" not in token:
        match = re.match(r"^(.*\d)([+-]\d{3})$", token)
        if match:
            token = f"{match.group(1)}E{match.group(2)}"
    return float(token.replace("D", "E"))


def _load_numeric_tokens(path: Path) -> np.ndarray:
    return np.asarray([_parse_legacy_float_token(token) for token in path.read_text().split()], dtype=float)


def _assert_exact_text(ref_dir: Path, jax_dir: Path, names: list[str]) -> None:
    for name in names:
        assert (ref_dir / name).read_text() == (jax_dir / name).read_text(), name


def _assert_numeric_close(ref_dir: Path, jax_dir: Path, names: list[str], *, atol: float = 1e-12) -> None:
    for name in names:
        ref = _load_numeric_file(ref_dir / name)
        got = _load_numeric_file(jax_dir / name)
        assert ref.shape == got.shape, name
        assert np.allclose(ref, got, rtol=0.0, atol=atol), name


def _assert_tokenwise_close(
    ref_dir: Path,
    jax_dir: Path,
    names: list[str],
    *,
    rtol: float = 0.0,
    atol: float = 0.0,
) -> None:
    for name in names:
        ref = _load_numeric_tokens(ref_dir / name)
        got = _load_numeric_tokens(jax_dir / name)
        assert ref.shape == got.shape, name
        assert np.array_equal(np.isnan(ref), np.isnan(got)), f"{name}: NaN mask"
        assert np.array_equal(np.isposinf(ref), np.isposinf(got)), f"{name}: +inf mask"
        assert np.array_equal(np.isneginf(ref), np.isneginf(got)), f"{name}: -inf mask"
        assert np.allclose(ref, got, rtol=rtol, atol=atol, equal_nan=True), name


def _assert_neo_out_close(ref_path: Path, got_path: Path, *, rtol: float, atol: float = 1e-12) -> None:
    ref = np.loadtxt(ref_path)
    got = np.loadtxt(got_path)
    assert ref.shape == got.shape
    assert np.array_equal(ref[:, 0].astype(int), got[:, 0].astype(int))
    assert np.allclose(ref[:, 1:], got[:, 1:], rtol=rtol, atol=atol)


def _assert_neolog_close(ref_path: Path, got_path: Path, *, rtol: float, atol: float = 1e-12) -> None:
    ref_lines = [line.split() for line in ref_path.read_text().splitlines() if line.strip()]
    got_lines = [line.split() for line in got_path.read_text().splitlines() if line.strip()]
    assert len(ref_lines) == len(got_lines)
    for ref_tokens, got_tokens in zip(ref_lines, got_lines):
        assert len(ref_tokens) == len(got_tokens) == 8
        assert [int(tok) for tok in ref_tokens[:7]] == [int(tok) for tok in got_tokens[:7]]
        ref_val = _parse_legacy_float_token(ref_tokens[7])
        got_val = _parse_legacy_float_token(got_tokens[7])
        assert np.isclose(ref_val, got_val, rtol=rtol, atol=atol)


@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_landreman_matches_xneo(tmp_path: Path) -> None:
    fixture = REPO / "tests" / "fixtures" / "landreman_qa_lowres"
    extension = "LandremanPaul2021_QA_lowres"

    _copy_fixture_case(tmp_path, fixture_dir=fixture, extension=extension, control_name=f"neo_in.{extension}")

    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    assert sorted(path.name for path in ref_dir.iterdir()) == sorted(path.name for path in jax_dir.iterdir())
    _assert_exact_text(ref_dir, jax_dir, [f"neo_out.{extension}", f"neolog.{extension}"])


@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_mini_orbits_matches_xneo_outputs(tmp_path: Path) -> None:
    extension = "ORBITS_MINI"
    booz_src = REPO / "tests" / "fixtures" / "orbits" / "boozmn_ORBITS_FAST.nc"
    control_text = _make_control(
        out_file=f"neo_out.{extension}",
        surfaces=[96],
        theta_n=8,
        phi_n=8,
        npart=10,
        multra=2,
        write_output_files=1,
        write_integrate=1,
        write_diagnostic=1,
        cur_file=f"neo_cur.{extension}",
    )
    _copy_case(tmp_path, extension=extension, booz_src=booz_src, control_text=control_text)

    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    assert sorted(path.name for path in ref_dir.iterdir()) == sorted(path.name for path in jax_dir.iterdir())
    _assert_exact_text(
        ref_dir,
        jax_dir,
        [
            f"neo_out.{extension}",
            "diagnostic.dat",
            "diagnostic_add.dat",
            "diagnostic_bigint.dat",
            "conver.dat",
            f"neolog.{extension}",
        ],
    )
    _assert_numeric_close(
        ref_dir,
        jax_dir,
        [
            "dimension.dat",
            "es_arr.dat",
            "mn_arr.dat",
            "rmnc_arr.dat",
            "zmns_arr.dat",
            "lmns_arr.dat",
            "bmnc_arr.dat",
            "theta_arr.dat",
            "phi_arr.dat",
            "b_s_arr.dat",
            "r_s_arr.dat",
            "z_s_arr.dat",
            "l_s_arr.dat",
            "isqrg_arr.dat",
            "sqrg11_arr.dat",
            "kg_arr.dat",
            "pard_arr.dat",
            "r_tb_arr.dat",
            "z_tb_arr.dat",
            "p_tb_arr.dat",
            "b_tb_arr.dat",
            "r_pb_arr.dat",
            "z_pb_arr.dat",
            "p_pb_arr.dat",
            "b_pb_arr.dat",
            "gtbtb_arr.dat",
            "gpbpb_arr.dat",
            "gtbpb_arr.dat",
        ],
        atol=5e-13,
    )


@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_calc_cur_matches_xneo(tmp_path: Path) -> None:
    extension = "ORBITS_CURINT"
    booz_src = REPO / "tests" / "fixtures" / "orbits" / "boozmn_ORBITS_FAST.nc"
    control_text = _make_control(
        out_file=f"neo_out.{extension}",
        surfaces=[96],
        theta_n=8,
        phi_n=8,
        npart=10,
        multra=1,
        calc_cur=1,
        cur_file=f"neo_cur.{extension}",
        npart_cur=100,
        alpha_cur=2.0,
        write_cur_inte=1,
    )
    _copy_case(tmp_path, extension=extension, booz_src=booz_src, control_text=control_text)

    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    _assert_exact_text(ref_dir, jax_dir, [f"neo_out.{extension}", f"neo_cur.{extension}", f"neolog.{extension}"])
    _assert_tokenwise_close(ref_dir, jax_dir, ["current.dat"], rtol=2e-7, atol=1e-10)


@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_ncsx_mini_matches_xneo(tmp_path: Path) -> None:
    extension = "NCSX_MINI"
    booz_src = REPO / "tests" / "fixtures" / "ncsx" / "boozmn_ncsx_c09r00_free.nc"
    control_text = _make_control(
        out_file=f"neo_out.{extension}",
        surfaces=[59],
        theta_n=8,
        phi_n=8,
        npart=10,
        multra=1,
        cur_file=f"neo_cur.{extension}",
    )
    _copy_case(tmp_path, extension=extension, booz_src=booz_src, control_text=control_text)

    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    _assert_exact_text(ref_dir, jax_dir, [f"neo_out.{extension}", f"neolog.{extension}"])


@pytest.mark.skipif(not RUN_SLOW, reason="Set NEO_JAX_RUN_SLOW=1 to run full ORBITS fixture parity.")
@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_orbits_fast_fixture_matches_xneo(tmp_path: Path) -> None:
    fixture = REPO / "tests" / "fixtures" / "orbits"
    extension = "ORBITS_FAST"

    _copy_fixture_case(tmp_path, fixture_dir=fixture, extension=extension, control_name=f"neo_in.{extension}")
    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    _assert_exact_text(ref_dir, jax_dir, [f"neo_out.{extension}", f"neolog.{extension}"])


@pytest.mark.skipif(not RUN_SLOW, reason="Set NEO_JAX_RUN_SLOW=1 to run full NCSX fixture parity.")
@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_ncsx_fast_fixture_matches_xneo(tmp_path: Path) -> None:
    fixture = REPO / "tests" / "fixtures" / "ncsx"
    extension = "ncsx_c09r00_free_fast"

    _copy_fixture_case(
        tmp_path,
        fixture_dir=fixture,
        extension=extension,
        control_name=f"neo_in.{extension}",
        booz_name="boozmn_ncsx_c09r00_free.nc",
    )
    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    _assert_neo_out_close(ref_dir / f"neo_out.{extension}", jax_dir / f"neo_out.{extension}", rtol=5.1e-3)
    _assert_neolog_close(ref_dir / f"neolog.{extension}", jax_dir / f"neolog.{extension}", rtol=5.1e-3)


@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_prefers_neo_param_extension_over_neo_in_extension(tmp_path: Path) -> None:
    extension = "PARAM_EXT"
    booz_src = REPO / "tests" / "fixtures" / "orbits" / "boozmn_ORBITS_FAST.nc"
    chosen = _make_control(out_file="neo_out.param_ext", surfaces=[96], theta_n=8, phi_n=8, npart=10, cur_file="neo_cur.param_ext")
    ignored = _make_control(out_file="neo_out.neo_in_ext", surfaces=[64], theta_n=8, phi_n=8, npart=10, cur_file="neo_cur.neo_in_ext")
    _copy_case(
        tmp_path,
        extension=extension,
        booz_src=booz_src,
        control_text=chosen,
        control_filename=f"neo_param.{extension}",
        extra_controls={f"neo_in.{extension}": ignored},
    )

    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    assert (ref_dir / "neo_out.param_ext").exists()
    assert (jax_dir / "neo_out.param_ext").exists()
    assert not (ref_dir / "neo_out.neo_in_ext").exists()
    assert not (jax_dir / "neo_out.neo_in_ext").exists()
    _assert_exact_text(ref_dir, jax_dir, ["neo_out.param_ext", f"neolog.{extension}"])


@pytest.mark.skipif(not REFERENCE_BIN.exists(), reason=f"Reference xneo binary not found at {REFERENCE_BIN}")
def test_cli_prefers_neo_param_in_over_neo_in_extension(tmp_path: Path) -> None:
    extension = "PARAM_IN"
    booz_src = REPO / "tests" / "fixtures" / "orbits" / "boozmn_ORBITS_FAST.nc"
    chosen = _make_control(out_file="neo_out.param_in", surfaces=[96], theta_n=8, phi_n=8, npart=10, cur_file="neo_cur.param_in")
    ignored = _make_control(out_file="neo_out.neo_in_param_in", surfaces=[64], theta_n=8, phi_n=8, npart=10, cur_file="neo_cur.neo_in_param_in")
    _copy_case(
        tmp_path,
        extension=extension,
        booz_src=booz_src,
        control_text=chosen,
        control_filename="neo_param.in",
        extra_controls={f"neo_in.{extension}": ignored},
    )

    ref_dir, jax_dir = _run_neo_pair(tmp_path, extension=extension)
    assert (ref_dir / "neo_out.param_in").exists()
    assert (jax_dir / "neo_out.param_in").exists()
    assert not (ref_dir / "neo_out.neo_in_param_in").exists()
    assert not (jax_dir / "neo_out.neo_in_param_in").exists()
    _assert_exact_text(ref_dir, jax_dir, ["neo_out.param_in", f"neolog.{extension}"])


def test_cli_progress_logging_and_quiet_flag(tmp_path: Path) -> None:
    extension = "LOG_MINI"
    booz_src = REPO / "tests" / "fixtures" / "orbits" / "boozmn_ORBITS_FAST.nc"
    control_text = _make_control(
        out_file=f"neo_out.{extension}",
        surfaces=[96],
        theta_n=6,
        phi_n=6,
        npart=4,
        multra=1,
        nstep_per=4,
        nstep_min=8,
        nstep_max=12,
        no_bins=8,
        cur_file=f"neo_cur.{extension}",
    )
    case_dir = _copy_single_cli_case(tmp_path, extension=extension, booz_src=booz_src, control_text=control_text)

    env = os.environ.copy()
    env["PYTHONPATH"] = str(REPO)

    verbose_run = subprocess.run(
        ["python", "-m", "neo_jax", extension],
        cwd=case_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )
    quiet_run = subprocess.run(
        ["python", "-m", "neo_jax", extension, "--quiet"],
        cwd=case_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )

    assert "NEO_JAX: starting legacy CLI solve" in verbose_run.stdout
    assert "NEO_JAX: surface 1/1" in verbose_run.stdout
    assert "NEO_JAX: wrote neo_out.LOG_MINI" in verbose_run.stdout
    assert quiet_run.stdout.strip() == ""
