"""Optional GPU smoke tests for the NEO_JAX Python API and legacy CLI."""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

import jax
import numpy as np
import pytest


REPO = Path(__file__).resolve().parents[2]
RUN_GPU = bool(os.environ.get("NEO_JAX_RUN_GPU"))
HAS_GPU = any(device.platform == "gpu" for device in jax.devices())

pytestmark = pytest.mark.skipif(
    not RUN_GPU or not HAS_GPU,
    reason="Set NEO_JAX_RUN_GPU=1 on a machine with a visible JAX GPU backend.",
)


def _make_control(*, out_file: str, surfaces: list[int], cur_file: str) -> str:
    flux_line = " ".join(str(v) for v in surfaces)
    return "\n".join(
        [
            "! autogenerated GPU smoke case",
            "! line2",
            "! line3",
            "boozmn",
            out_file,
            str(len(surfaces)),
            flux_line,
            "8",
            "8",
            "0",
            "0",
            "10",
            "1",
            "0.05",
            "10",
            "5",
            "10",
            "20",
            "0",
            "1",
            "0",
            "0",
            "2",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            cur_file,
            "200",
            "2.0",
            "0",
            "",
        ]
    )


def _parse_legacy_float_token(token: str) -> float:
    if token == "NaN":
        return float("nan")
    if token in {"Infinity", "+Infinity"}:
        return float("inf")
    if token == "-Infinity":
        return float("-inf")
    if "E" not in token and "D" not in token and token[-4:-3] in {"+", "-"}:
        token = f"{token[:-4]}E{token[-4:]}"
    return float(token.replace("D", "E"))


def _load_legacy_numbers(path: Path) -> np.ndarray:
    return np.asarray([_parse_legacy_float_token(token) for token in path.read_text().split()], dtype=float)


def _run_subprocess(
    args: list[str],
    *,
    cwd: Path,
    platform: str,
    pythonpath: str | None = None,
) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["JAX_PLATFORM_NAME"] = platform
    env["NEO_JAX_ENABLE_X64"] = "1"
    if pythonpath is not None:
        env["PYTHONPATH"] = pythonpath
    return subprocess.run(
        [sys.executable, *args],
        cwd=cwd,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )


def test_cli_matches_between_cpu_and_gpu(tmp_path: Path) -> None:
    extension = "GPU_MINI"
    fixture_dir = REPO / "tests" / "fixtures" / "orbits"
    control_text = _make_control(out_file=f"neo_out.{extension}", surfaces=[96], cur_file=f"neo_cur.{extension}")

    cpu_dir = tmp_path / "cpu"
    gpu_dir = tmp_path / "gpu"
    for target in (cpu_dir, gpu_dir):
        target.mkdir()
        (target / f"neo_in.{extension}").write_text(control_text, encoding="utf-8")
        shutil.copy2(fixture_dir / "boozmn_ORBITS_FAST.nc", target / f"boozmn_{extension}.nc")

    cpu_run = _run_subprocess(
        ["-m", "neo_jax", extension],
        cwd=cpu_dir,
        platform="cpu",
        pythonpath=str(REPO),
    )
    gpu_run = _run_subprocess(
        ["-m", "neo_jax", extension],
        cwd=gpu_dir,
        platform="gpu",
        pythonpath=str(REPO),
    )

    assert "NEO_JAX: jax_runtime=cpu" in cpu_run.stdout
    assert "NEO_JAX: jax_runtime=gpu" in gpu_run.stdout

    cpu_values = _load_legacy_numbers(cpu_dir / f"neo_out.{extension}")
    gpu_values = _load_legacy_numbers(gpu_dir / f"neo_out.{extension}")
    assert cpu_values.shape == gpu_values.shape
    assert np.allclose(cpu_values, gpu_values, rtol=1e-9, atol=1e-12)


def test_python_api_matches_between_cpu_and_gpu(tmp_path: Path) -> None:
    script = tmp_path / "run_api.py"
    script.write_text(
        """
import json
from pathlib import Path

import jax

from neo_jax import NeoConfig, neo_outputs_to_results, run_neo

repo = Path(__file__).resolve().parents[0]
boozmn = repo / "boozmn_ORBITS_FAST.nc"
cfg = NeoConfig(
    surfaces=[0.8],
    theta_n=8,
    phi_n=8,
    npart=10,
    multra=1,
    acc_req=0.05,
    no_bins=10,
    nstep_per=5,
    nstep_min=10,
    nstep_max=20,
)
outputs = run_neo(boozmn, config=cfg, use_jax=True, jax_surface_scan=True, progress=False)
results = neo_outputs_to_results(outputs)
print(
    json.dumps(
        {
            "backend": jax.default_backend(),
            "epsilon_effective": results.epsilon_effective.tolist(),
            "s": results.s.tolist(),
            "sqrt_s": results.sqrt_s.tolist(),
            "r_eff": results.r_eff.tolist(),
        }
    )
)
        """.strip(),
        encoding="utf-8",
    )
    shutil.copy2(REPO / "tests" / "fixtures" / "orbits" / "boozmn_ORBITS_FAST.nc", tmp_path / "boozmn_ORBITS_FAST.nc")

    cpu_run = _run_subprocess(
        [str(script)],
        cwd=tmp_path,
        platform="cpu",
        pythonpath=str(REPO),
    )
    gpu_run = _run_subprocess(
        [str(script)],
        cwd=tmp_path,
        platform="gpu",
        pythonpath=str(REPO),
    )

    cpu_payload = json.loads(cpu_run.stdout)
    gpu_payload = json.loads(gpu_run.stdout)

    assert cpu_payload["backend"] == "cpu"
    assert gpu_payload["backend"] == "gpu"
    assert np.allclose(cpu_payload["epsilon_effective"], gpu_payload["epsilon_effective"], rtol=1e-9, atol=1e-12)
    assert np.allclose(cpu_payload["s"], gpu_payload["s"], rtol=0.0, atol=0.0)
    assert np.allclose(cpu_payload["sqrt_s"], gpu_payload["sqrt_s"], rtol=0.0, atol=0.0)
    assert np.allclose(cpu_payload["r_eff"], gpu_payload["r_eff"], rtol=1e-12, atol=1e-12)
