"""Legacy CLI parity tests against stored ``xneo`` reference fixtures."""

from __future__ import annotations

import gzip
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

import numpy as np
import pytest

from neo_jax.fixtures import ncsx_boozmn_path


REPO = Path(__file__).resolve().parents[2]
FIXTURES = REPO / "tests" / "fixtures"
CLI_FIXTURES = FIXTURES / "cli_legacy"


def _format_control_scalar(value: float | int | str) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, int):
        return str(value)
    return format(float(value), ".15g")


def _make_control(
    *,
    out_file: str,
    surfaces: list[int],
    theta_n: int = 8,
    phi_n: int = 8,
    max_m_mode: int = 0,
    max_n_mode: int = 0,
    npart: int = 10,
    multra: int = 1,
    acc_req: float = 0.05,
    no_bins: int = 10,
    nstep_per: int = 5,
    nstep_min: int = 10,
    nstep_max: int = 20,
    calc_nstep_max: int = 0,
    eout_swi: int = 1,
    lab_swi: int = 0,
    inp_swi: int = 0,
    ref_swi: int = 2,
    write_progress: int = 0,
    write_output_files: int = 0,
    spline_test: int = 0,
    write_integrate: int = 0,
    write_diagnostic: int = 0,
    calc_cur: int = 0,
    cur_file: str = "neo_cur",
    npart_cur: int = 200,
    alpha_cur: float = 2.0,
    write_cur_inte: int = 0,
) -> str:
    flux_line = " ".join(str(v) for v in surfaces)
    no_fluxs = len(surfaces)
    return "\n".join(
        [
            "! autogenerated legacy parity case",
            "! line2",
            "! line3",
            "boozmn",
            out_file,
            str(no_fluxs),
            flux_line,
            str(theta_n),
            str(phi_n),
            str(max_m_mode),
            str(max_n_mode),
            str(npart),
            str(multra),
            _format_control_scalar(acc_req),
            str(no_bins),
            str(nstep_per),
            str(nstep_min),
            str(nstep_max),
            str(calc_nstep_max),
            str(eout_swi),
            str(lab_swi),
            str(inp_swi),
            str(ref_swi),
            str(write_progress),
            str(write_output_files),
            str(spline_test),
            str(write_integrate),
            str(write_diagnostic),
            "0",
            "0",
            "0",
            str(calc_cur),
            cur_file,
            str(npart_cur),
            _format_control_scalar(alpha_cur),
            str(write_cur_inte),
            "",
        ]
    )


def _copy_case(
    tmp_path: Path,
    *,
    extension: str,
    booz_src: Path,
    control_text: str,
    control_filename: str | None = None,
    extra_controls: dict[str, str] | None = None,
) -> Path:
    case_dir = tmp_path / "case"
    case_dir.mkdir(exist_ok=True)
    control_filename = control_filename or f"neo_in.{extension}"
    (case_dir / control_filename).write_text(control_text, encoding="utf-8")
    shutil.copy2(booz_src, case_dir / f"boozmn_{extension}.nc")
    if extra_controls:
        for name, text in extra_controls.items():
            (case_dir / name).write_text(text, encoding="utf-8")
    return case_dir


def _copy_reference_case(
    tmp_path: Path,
    *,
    fixture_dir: Path,
    extension: str,
    booz_src: Path,
    control_name: str | None = None,
) -> Path:
    control_name = control_name or f"neo_in.{extension}"
    case_dir = tmp_path / "case"
    case_dir.mkdir(exist_ok=True)
    shutil.copy2(fixture_dir / control_name, case_dir / control_name)
    shutil.copy2(booz_src, case_dir / f"boozmn_{extension}.nc")
    return case_dir


def _run_cli(case_dir: Path, extension: str, *extra_args: str) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(REPO)
    return subprocess.run(
        [sys.executable, "-m", "neo_jax", extension, *extra_args],
        cwd=case_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )


def _read_text(path: Path) -> str:
    if path.suffix == ".gz":
        with gzip.open(path, "rt", encoding="utf-8") as stream:
            return stream.read()
    return path.read_text()


def _load_numeric_file(path: Path) -> np.ndarray:
    return np.fromstring(_read_text(path).replace("D", "E"), sep=" ")


def _parse_legacy_float_token(token: str) -> float:
    if token == "NaN":
        return float("nan")
    if token in {"Infinity", "+Infinity"}:
        return float("inf")
    if token == "-Infinity":
        return float("-inf")
    if "E" not in token and "D" not in token:
        match = re.match(r"^(.*\d)([+-]\d{3})$", token)
        if match:
            token = f"{match.group(1)}E{match.group(2)}"
    return float(token.replace("D", "E"))


def _load_numeric_tokens(path: Path) -> np.ndarray:
    return np.asarray([_parse_legacy_float_token(token) for token in _read_text(path).split()], dtype=float)


def _ncsx_boozmn_or_skip() -> Path:
    try:
        return ncsx_boozmn_path(download=False)
    except FileNotFoundError as exc:
        pytest.skip(str(exc))


def _assert_exact_text(reference_dir: Path, case_dir: Path, names: list[str]) -> None:
    for name in names:
        assert (reference_dir / name).read_text() == (case_dir / name).read_text(), name


def _assert_numeric_close(reference_dir: Path, case_dir: Path, names: list[str], *, atol: float = 1e-12) -> None:
    for name in names:
        ref = _load_numeric_file(reference_dir / name)
        got = _load_numeric_file(case_dir / name)
        assert ref.shape == got.shape, name
        assert np.allclose(ref, got, rtol=0.0, atol=atol), name


def _assert_tokenwise_close(
    reference_dir: Path,
    case_dir: Path,
    names: list[str],
    *,
    rtol: float = 0.0,
    atol: float = 0.0,
) -> None:
    for name in names:
        ref = _load_numeric_tokens(reference_dir / name)
        got = _load_numeric_tokens(case_dir / name)
        assert ref.shape == got.shape, name
        assert np.array_equal(np.isnan(ref), np.isnan(got)), f"{name}: NaN mask"
        assert np.array_equal(np.isposinf(ref), np.isposinf(got)), f"{name}: +inf mask"
        assert np.array_equal(np.isneginf(ref), np.isneginf(got)), f"{name}: -inf mask"
        assert np.allclose(ref, got, rtol=rtol, atol=atol, equal_nan=True), name


def test_cli_landreman_matches_reference_fixture(tmp_path: Path) -> None:
    fixture = FIXTURES / "landreman_qa_lowres"
    extension = "LandremanPaul2021_QA_lowres"

    case_dir = _copy_reference_case(
        tmp_path,
        fixture_dir=fixture,
        extension=extension,
        booz_src=fixture / f"boozmn_{extension}.nc",
    )

    _run_cli(case_dir, extension, "--quiet")
    _assert_exact_text(fixture, case_dir, [f"neo_out.{extension}", f"neolog.{extension}"])


def test_cli_orbits_mini_matches_reference_fixture(tmp_path: Path) -> None:
    reference_dir = CLI_FIXTURES / "orbits_mini"
    extension = "ORBITS_MINI"
    case_dir = _copy_reference_case(
        tmp_path,
        fixture_dir=reference_dir,
        extension=extension,
        booz_src=FIXTURES / "orbits" / "boozmn_ORBITS_FAST.nc",
    )

    _run_cli(case_dir, extension, "--quiet")

    reference_outputs = {
        path.name
        for path in reference_dir.iterdir()
        if path.is_file() and path.name not in {"README.md", f"neo_in.{extension}"}
    }
    produced_outputs = {path.name for path in case_dir.iterdir() if path.is_file() and path.name != f"neo_in.{extension}"}

    assert produced_outputs.issuperset(reference_outputs)
    assert {
        "diagnostic_bigint.dat",
        "diagnostic_first_trap.dat",
        "b_pb_arr.dat",
        "b_tb_arr.dat",
        "gtbtb_arr.dat",
        "gpbpb_arr.dat",
        "gtbpb_arr.dat",
    }.issubset(produced_outputs)

    _assert_exact_text(
        reference_dir,
        case_dir,
        [
            f"neo_out.{extension}",
            "diagnostic.dat",
            "diagnostic_add.dat",
            "conver.dat",
            f"neolog.{extension}",
        ],
    )
    _assert_numeric_close(
        reference_dir,
        case_dir,
        [
            "dimension.dat",
            "es_arr.dat",
            "mn_arr.dat",
            "rmnc_arr.dat",
            "zmns_arr.dat",
            "lmns_arr.dat",
            "bmnc_arr.dat",
            "theta_arr.dat",
            "phi_arr.dat",
            "b_s_arr.dat",
            "r_s_arr.dat",
            "z_s_arr.dat",
            "l_s_arr.dat",
            "isqrg_arr.dat",
            "sqrg11_arr.dat",
            "kg_arr.dat",
            "pard_arr.dat",
        ],
        atol=1e-14,
    )


def test_cli_calc_cur_matches_reference_fixture(tmp_path: Path) -> None:
    reference_dir = CLI_FIXTURES / "orbits_curint"
    extension = "ORBITS_CURINT"
    case_dir = _copy_reference_case(
        tmp_path,
        fixture_dir=reference_dir,
        extension=extension,
        booz_src=FIXTURES / "orbits" / "boozmn_ORBITS_FAST.nc",
    )

    _run_cli(case_dir, extension, "--quiet")

    reference_outputs = {
        "current.dat" if path.name == "current.dat.gz" else path.name
        for path in reference_dir.iterdir()
        if path.is_file() and path.name not in {"README.md", f"neo_in.{extension}"}
    }
    produced_outputs = {path.name for path in case_dir.iterdir() if path.is_file() and path.name != f"neo_in.{extension}"}

    assert produced_outputs.issuperset(reference_outputs)
    _assert_exact_text(reference_dir, case_dir, [f"neo_out.{extension}", f"neo_cur.{extension}", f"neolog.{extension}"])
    ref = _load_numeric_tokens(reference_dir / "current.dat.gz")
    got = _load_numeric_tokens(case_dir / "current.dat")
    assert ref.shape == got.shape
    assert np.array_equal(np.isnan(ref), np.isnan(got)), "current.dat: NaN mask"
    assert np.array_equal(np.isposinf(ref), np.isposinf(got)), "current.dat: +inf mask"
    assert np.array_equal(np.isneginf(ref), np.isneginf(got)), "current.dat: -inf mask"
    assert np.allclose(ref, got, rtol=1e-4, atol=1e-10, equal_nan=True), "current.dat"


def test_cli_ncsx_mini_matches_reference_fixture(tmp_path: Path) -> None:
    reference_dir = CLI_FIXTURES / "ncsx_mini"
    extension = "NCSX_MINI"
    case_dir = _copy_reference_case(
        tmp_path,
        fixture_dir=reference_dir,
        extension=extension,
        booz_src=_ncsx_boozmn_or_skip(),
    )

    _run_cli(case_dir, extension, "--quiet")
    _assert_exact_text(reference_dir, case_dir, [f"neo_out.{extension}", f"neolog.{extension}"])


def test_cli_prefers_neo_param_extension_over_neo_in_extension(tmp_path: Path) -> None:
    extension = "PARAM_EXT"
    booz_src = FIXTURES / "orbits" / "boozmn_ORBITS_FAST.nc"
    chosen = _make_control(out_file="neo_out.param_ext", surfaces=[96], theta_n=8, phi_n=8, npart=10, cur_file="neo_cur.param_ext")
    ignored = _make_control(
        out_file="neo_out.neo_in_ext",
        surfaces=[64],
        theta_n=8,
        phi_n=8,
        npart=10,
        cur_file="neo_cur.neo_in_ext",
    )
    case_dir = _copy_case(
        tmp_path,
        extension=extension,
        booz_src=booz_src,
        control_text=chosen,
        control_filename=f"neo_param.{extension}",
        extra_controls={f"neo_in.{extension}": ignored},
    )

    _run_cli(case_dir, extension, "--quiet")
    assert (case_dir / "neo_out.param_ext").exists()
    assert not (case_dir / "neo_out.neo_in_ext").exists()


def test_cli_prefers_neo_param_in_over_neo_in_extension(tmp_path: Path) -> None:
    extension = "PARAM_IN"
    booz_src = FIXTURES / "orbits" / "boozmn_ORBITS_FAST.nc"
    chosen = _make_control(out_file="neo_out.param_in", surfaces=[96], theta_n=8, phi_n=8, npart=10, cur_file="neo_cur.param_in")
    ignored = _make_control(
        out_file="neo_out.neo_in_param_in",
        surfaces=[64],
        theta_n=8,
        phi_n=8,
        npart=10,
        cur_file="neo_cur.neo_in_param_in",
    )
    case_dir = _copy_case(
        tmp_path,
        extension=extension,
        booz_src=booz_src,
        control_text=chosen,
        control_filename="neo_param.in",
        extra_controls={f"neo_in.{extension}": ignored},
    )

    _run_cli(case_dir, extension, "--quiet")
    assert (case_dir / "neo_out.param_in").exists()
    assert not (case_dir / "neo_out.neo_in_param_in").exists()


def test_cli_progress_logging_and_quiet_flag(tmp_path: Path) -> None:
    extension = "LOG_MINI"
    control_text = _make_control(
        out_file=f"neo_out.{extension}",
        surfaces=[96],
        theta_n=2,
        phi_n=2,
        npart=2,
        multra=1,
        nstep_per=2,
        nstep_min=4,
        nstep_max=6,
        no_bins=4,
        cur_file=f"neo_cur.{extension}",
    )
    case_dir = _copy_case(
        tmp_path,
        extension=extension,
        booz_src=FIXTURES / "orbits" / "boozmn_ORBITS_FAST.nc",
        control_text=control_text,
    )

    verbose_run = _run_cli(case_dir, extension)
    quiet_run = _run_cli(case_dir, extension, "--quiet")

    assert "NEO_JAX: starting legacy CLI solve" in verbose_run.stdout
    assert "NEO_JAX: jax_runtime=cpu" in verbose_run.stdout
    assert "NEO_JAX: surface 1/1" in verbose_run.stdout
    assert f"NEO_JAX: wrote neo_out.{extension}" in verbose_run.stdout
    assert "NEO_JAX:" not in quiet_run.stdout


def test_cli_ipmax_debug_dump(tmp_path: Path) -> None:
    extension = "IPMAX_MINI"
    control_text = _make_control(
        out_file=f"neo_out.{extension}",
        surfaces=[96],
        theta_n=4,
        phi_n=4,
        npart=4,
        multra=1,
        nstep_per=4,
        nstep_min=8,
        nstep_max=12,
        no_bins=8,
        write_integrate=1,
        cur_file=f"neo_cur.{extension}",
    )
    case_dir = _copy_case(
        tmp_path,
        extension=extension,
        booz_src=FIXTURES / "orbits" / "boozmn_ORBITS_FAST.nc",
        control_text=control_text,
    )

    env = os.environ.copy()
    env["PYTHONPATH"] = str(REPO)
    env["NEO_JAX_WRITE_IPMAX_DEBUG"] = "1"

    subprocess.run(
        [sys.executable, "-m", "neo_jax", extension, "--quiet"],
        cwd=case_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )

    debug_path = case_dir / "diagnostic_ipmax_jax.dat"
    assert debug_path.exists()
    assert debug_path.read_text().strip() != ""
